---
model_architecture: TransformerPriorCoderSideInfoAtDecodeConcat

model_params:
    num_filters: 192
    num_features: 192
    num_hyperpriors: 192
    in_channels: 3
    out_channels: 3
    kernel_size: 5
    w_c: 4
    w_p: 8
    d_C: 192
    d_T: 192
    d_trg_vocab: 384
    condition: Gaussian
    quant_mode: noise
