---
model_architecture: TransformerPriorCoder

model_params:
    num_filters: 192
    num_features: 192
    num_hyperpriors: 192
    in_channels: 3
    out_channels: 3
    kernel_size: 5
    w_c: 4
    w_p: 8
    d_C: 192
    d_T: 768
    d_inner: 2048
    condition: Gaussian
    quant_mode: noise
